# Generated by Django 3.1.5 on 2021-01-10 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('katuapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'verbose_name_plural': 'Diary'},
        ),
    ]
